version: "3.9"

services:
  web:
    build: .
    container_name: mlflow-fastapi-khatir-youyou
    network_mode: host
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://127.0.0.1:8080}
    restart: unless-stopped

